name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          $CC nobuild.c -o nobuild
          ./nobuild
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          $CC nobuild.c -o nobuild
          ./nobuild
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          $CC nobuild.c -o nobuild
          ./nobuild
        env:
          CC: clang
          CXX: clang++
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        shell: cmd
        # this replaces default PowerShell, which can't fail the build
        run: |
          cl.exe nobuild.c
          .\nobuild.exe test
